define({
     "root"  :  [
                  {"name":"Widget_Pages","package":"Pages","demos":[
                                                                 {'name':'Widget_Pages_Demo1','page':'1'},
                                                                 {'name':'Widget_Pages_Demo2','page':'2'},
                                                                 {'name':'Widget_Pages_Demo3','page':'3'},
                                                                 {'name':'Widget_Pages_Demo4','page':'4'},
                                                                 {'name':'Widget_Pages_Demo5','page':'5'}
                                                                ]
                  },
                  {"name":"Widget_Loader","package":"Loader","demos":[
                                                                 {'name':'Widget_Loader_Demo1','page':'1'},
                                                                 {'name':'Widget_Loader_Demo2','page':'2'},
                                                                 {'name':'Widget_Loader_Demo3','page':'3'}
                                                                ]
                  },
                  {"name":"Widget_Tabs","package":"Tabs","demos":[
                                                                 {'name':'Widget_Tabs_Demo1','page':'1'},
                                                                 {'name':'Widget_Tabs_Demo2','page':'2'}
                                                                ]
                  },
                  {"name":"Widget_Popup","package":"Popup","demos":[
                                                                 {'name':'Widget_Popup_Demo1','page':'1'},
                                                                 {'name':'Widget_Popup_Demo2','page':'2'},
                                                                 {'name':'Widget_Popup_Demo3','page':'3'},
                                                                 {'name':'Widget_Popup_Demo4','page':'4'},
                                                                 {'name':'Widget_Popup_Demo5','page':'5'},
                                                                 {'name':'Widget_Popup_Demo6','page':'6'},
                                                                 {'name':'Widget_Popup_Demo7','page':'7'},
                                                                 /*{'name':'Widget_Popup_Demo8','page':'8'},*/
                                                                 {'name':'Widget_Popup_Demo9','page':'9'}/*,
                                                                 {'name':'Widget_Popup_Demo10','page':'10'}*/
                      
                                                                ]
                  },
                  {"name":"Widget_Listview","package":"Listview","demos":[
                                                                     {'name':'Widget_Listview_Demo1','page':'1'},
                                                                     {'name':'Widget_Listview_Demo2','page':'2'},
                                                                     {'name':'Widget_Listview_Demo3','page':'3'},
                                                                     {'name':'Widget_Listview_Demo4','page':'4'},
                                                                     {'name':'Widget_Listview_Demo5','page':'5'},
                                                                     {'name':'Widget_Listview_Demo6','page':'6'},
                                                                     {'name':'Widget_Listview_Demo7','page':'7'},
                                                                     {'name':'Widget_Listview_Demo8','page':'8'}/*,
                                                                     {'name':'Widget_Listview_Demo9','page':'9'}*/
                                                                    ]
                  },
                  {"name":"Widget_Collapsible","package":"Collapsible","demos":[
                                                                         {'name':'Widget_Collapsible_Demo1','page':'1'},
                                                                         {'name':'Widget_Collapsible_Demo2','page':'2'},
                                                                         {'name':'Widget_Collapsible_Demo3','page':'3'}
                                                                        ]
                  },
                  {"name":"Widget_Table","package":"Table","demos":[
                                                                 {'name':'Widget_Table_Demo1','page':'1'},
                                                                 {'name':'Widget_Table_Demo2','page':'2'}
                                                                ]
                  },
                  {"name":"Widget_Filterable","package":"Filterable","demos":[
                                                                         {'name':'Widget_Filterable_Demo1','page':'1'},
                                                                         {'name':'Widget_Filterable_Demo2','page':'2'},
                                                                         {'name':'Widget_Filterable_Demo3','page':'3'},
                                                                         {'name':'Widget_Filterable_Demo4','page':'4'}
                                                                        ]
                  },
                  {"name":"Widget_Checkbox","package":"Checkbox","demos":[
                                                                     {'name':'Widget_Checkbox_Demo1','page':'1'},
                                                                     {'name':'Widget_Checkbox_Demo2','page':'2'},
                                                                     {'name':'Widget_Checkbox_Demo3','page':'3'}
                                                                    ]
                  },
                  {"name":"Widget_RadioButtons","package":"RadioButtons","demos":[
                                                                         {'name':'Widget_RadioButtons_Demo1','page':'1'},
                                                                         {'name':'Widget_RadioButtons_Demo2','page':'2'},
                                                                         {'name':'Widget_RadioButtons_Demo3','page':'3'}
                                                                        ]
                  },
                  {"name":"Widget_SelectMenu","package":"SelectMenu","demos":[
                                                                         {'name':'Widget_SelectMenu_Demo1','page':'1'},
                                                                         {'name':'Widget_SelectMenu_Demo2','page':'2'},
                                                                         {'name':'Widget_SelectMenu_Demo3','page':'3'},
                                                                         {'name':'Widget_SelectMenu_Demo4','page':'4'},
                                                                         {'name':'Widget_SelectMenu_Demo5','page':'5'},
                                                                         {'name':'Widget_SelectMenu_Demo6','page':'6'}
                                                                        ]
                  },
                  {"name":"Widget_FlipSwitch","package":"FlipSwitch","demos":[
                                                                         {'name':'Widget_FlipSwitch_Demo1','page':'1'},
                                                                         {'name':'Widget_FlipSwitch_Demo2','page':'2'}
                                                                        ]
                  },
                  {"name":"Widget_Slider","package":"Slider","demos":[
                                                                     {'name':'Widget_Slider_Demo1','page':'1'},
                                                                     {'name':'Widget_Slider_Demo2','page':'2'},
                                                                     {'name':'Widget_Slider_Demo3','page':'3'}
                                                                    ]
                  },
                  {"name":"Widget_InputButtons","package":"InputButtons","demos":[
                                                                         {'name':'Widget_InputButtons_Demo1','page':'1'},
                                                                         {'name':'Widget_InputButtons_Demo2','page':'2'},
                                                                         {'name':'Widget_InputButtons_Demo3','page':'3'},
                                                                         {'name':'Widget_InputButtons_Demo4','page':'4'},
                                                                         {'name':'Widget_InputButtons_Demo5','page':'5'}
                                                                        ]
                  },
                  {"name":"Widget_TextInputs","package":"TextInputs","demos":[
                                                                         {'name':'Widget_TextInputs_Demo1','page':'1'},
                                                                         {'name':'Widget_TextInputs_Demo2','page':'2'},
                                                                         {'name':'Widget_TextInputs_Demo3','page':'3'},
                                                                         {'name':'Widget_TextInputs_Demo4','page':'4'},
                                                                         {'name':'Widget_TextInputs_Demo5','page':'5'},
                                                                         {'name':'Widget_TextInputs_Demo6','page':'6'},
                                                                         {'name':'Widget_TextInputs_Demo7','page':'7'}
                                                                        ]
                  },
                  {"name":"Widget_Grids","package":"Grids","demos":[
                                                                     {'name':'Widget_Grids_Demo1','page':'1'},
                                                                     {'name':'Widget_Grids_Demo2','page':'2'},
                                                                     {'name':'Widget_Grids_Demo3','page':'3'},
                                                                     {'name':'Widget_Grids_Demo4','page':'4'}
                                                                    ]
                  },
                  {"name":"Widget_ContentBlock","package":"ContentBlock","demos":[
                                                     {'name':'Widget_ContentBlock_Demo1','page':'1'},
                                                     {'name':'Widget_ContentBlock_Demo2','page':'2'},
                                                     {'name':'Widget_ContentBlock_Demo3','page':'3'}
                                                    ]
                  },
                  {"name":"Widget_Form","package":"Form","demos":[
                                                     {'name':'Widget_Form_Demo1','page':'1'},
                                                     {'name':'Widget_Form_Demo2','page':'2'}
                                                    ]
                  }
                ]
});